name: test-backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: chase_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Cache Prisma binaries
      uses: actions/cache@v3
      id: prisma-cache
      with:
        path: ~/.cache/prisma
        key: ${{ runner.os }}-prisma-${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-prisma-

    - name: Install dependencies
      run: |
        cd backend
        bun install

    - name: Install Prisma CLI globally
      run: bun install -g prisma@6.11.1

    - name: Generate Prisma Client
      run: |
        cd backend
        prisma generate

    - name: Run database migrations
      run: |
        cd backend
        prisma migrate deploy
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/chase_test

    - name: Run tests
      run: |
        cd backend
        bun test
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/chase_test
        JWT_SECRET: test-secret-key
        NODE_ENV: test